"""empty message

Revision ID: 7e14c3ec4876
Revises: f8a6706f30ff
Create Date: 2026-08-01 17:14:02.643033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e14c3ec4876'
down_revision: Union[str, Sequence[str], None] = 'f8a6706f30ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_documents', sa.Column('conversation_id', sa.Integer(), nullable=True))
    op.add_column('conversation_documents', sa.Column('document_id', sa.Integer(), nullable=True))
    op.add_column('conversation_documents', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_foreign_key(None, 'conversation_documents', 'conversations', ['conversation_id'], ['id'])
    op.create_foreign_key(None, 'conversation_documents', 'documents', ['document_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversation_documents', type_='foreignkey')
    op.drop_constraint(None, 'conversation_documents', type_='foreignkey')
    op.drop_column('conversation_documents', 'created_at')
    op.drop_column('conversation_documents', 'document_id')
    op.drop_column('conversation_documents', 'conversation_id')
    # ### end Alembic commands ###
