"""refresh token

Revision ID: a788d0249804
Revises: 9f81623989f0
Create Date: 2026-07-16 01:32:11.693622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a788d0249804'
down_revision: Union[str, Sequence[str], None] = '9f81623989f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refreshtoken')
    op.add_column('refresh_tokens', sa.Column('token', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'refresh_tokens', ['token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_tokens', type_='unique')
    op.drop_column('refresh_tokens', 'token')
    op.create_table('refreshtoken',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('refreshtoken_pkey'))
    )
    # ### end Alembic commands ###
