"""tile -> file in Document model

Revision ID: f8a6706f30ff
Revises: 0841800bd0ed
Create Date: 2026-07-21 11:37:32.144493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8a6706f30ff'
down_revision: Union[str, Sequence[str], None] = '0841800bd0ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_size', sa.BigInteger(), nullable=False))
    op.drop_column('documents', 'tile_size')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('tile_size', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_column('documents', 'file_size')
    # ### end Alembic commands ###
