name: AIBOT CI/CD

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Check Docker Version
        run: docker --version 
      
      - name: Build Docker Image
        run: docker build -t aibot-backend:ci .