name: AIBOT CI/CD

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read


    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Check Docker Version
        run: docker --version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Build Docker Image
        env:
          REGISTRY: ${{ steps.ecr-login.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/chatbot:$IMAGE_TAG .

      - name: Push Docker Image
        env:
          REGISTRY: ${{ steps.ecr-login.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker push $REGISTRY/chatbot:$IMAGE_TAG

  # cd:
  #   needs: ci
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Deploy to EC2
  #       uses: appleboy/ssh-action@v1.2.2
  #       with:
  #         host: ${{ secrets.EC2_HOST }}
  #         username: ${{ secrets.EC2_USER }}
  #         key: ${{ secrets.EC2_SSH_KEY }}
  #         script: |
  #           cd ~/chat-bot
  #           git pull origin main
  #           docker compose build backend
  #           docker compose up -d --force-recreate backend celery